apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Parsers_File  /fluent-bit/etc/parsers.conf

    [INPUT]
        Name tail
        Path /tmp/inference.log
        Tag triton-client
        Parser json

    [OUTPUT]
        Name  loki
        Match *
        Host  loki.logging.svc.cluster.local
        Port  3100
        URI   /loki/api/v1/push
        Labels job="triton-client"
        Line_format json
  parsers.conf: |
    [PARSER]
        Name        json
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S
