apiVersion: v1
kind: Pod
metadata:
  name: tritonclient-grpc
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  containers:
  - name: triton-grpc-client
    image: resnet/tritonclient:0.1.3
    env:
    - name: TRITON_URL
      value: "triton-server.default.svc.cluster.local:8001"
    - name: MODEL_NAME
      value: "resnet18-mnist_0.4.3"
    volumeMounts:
      - name: log-dir
        mountPath: /tmp
  - name: fluent-bit
    image: fluent/fluent-bit:latest
    volumeMounts:
      - name: log-dir
        mountPath: /tmp
      - name: config
        mountPath: /fluent-bit/etc/
  volumes:
    - name: log-dir
      emptyDir: {}
    - name: config
      configMap:
        name: fluent-bit-config
