apiVersion: batch/v1
kind: Job
metadata:
  name: train-job
spec:
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: resnet-training
        image: resnet/train-resnet18-mnist:0.4.3
        volumeMounts:
        - name: model-storage
          mountPath: /app/data
      restartPolicy: Never
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: dataset-pvc
